const en = {
  tabLabel: 'Update',
  tabDescription: 'Check for and install new ChatCMD versions.',
  categoryDescription: 'Manage app versions and updates from GitHub Releases.',
  introTitle: 'Update ChatCMD',
  introDescription: 'ChatCMD checks GitHub Releases and selects the correct package for your operating system and CPU architecture.',
  currentVersion: 'Current version',
  latestVersion: 'New version',
  release: 'GitHub release',
  platform: 'Platform',
  check: 'Check for updates',
  checking: 'Checking…',
  update: 'Update now',
  upToDate: 'You are using the latest version.',
  noPublishedVersion: 'No suitable GitHub release is currently available.',
  unavailable: 'A newer version exists, but no installer is available for this architecture.',
  releaseNotes: 'Release notes',
  openRelease: 'Open on GitHub',
  confirmTitle: 'Confirm update',
  confirmDescription: 'ChatCMD will download, verify, replace the application files, and then restart automatically.',
  confirmWarning: 'Are you sure you want to update? Make sure no conversation is active to avoid losing data.',
  cancel: 'Cancel',
  confirmUpdate: 'Confirm update',
  downloading: 'Downloading update from GitHub',
  verifying: 'Verifying SHA-256',
  extracting: 'Extracting update package',
  preparing: 'Preparing installation',
  ready: 'Update is ready',
  readyInstruction: 'The files were downloaded, verified, and prepared successfully. ChatCMD will restart to finish installation.',
  restart: 'Restart to finish',
  restarting: 'Closing and restarting ChatCMD…',
  failed: 'Update failed',
  retry: 'Try again',
  unsupported: 'Automatic updates are currently supported only on Windows and macOS.',
  popupTitle: 'A new ChatCMD update is available',
  popupDescription: 'GitHub Releases has a newer version for this device.',
  popupBadge: 'New update',
  popupTrust: 'The package is downloaded directly from GitHub Releases and SHA-256 is verified before application files are replaced.',
  goUpdate: 'Go to update',
  close: 'Close',
  downloadStep: 'Download',
  verifyStep: 'Verify',
  extractStep: 'Extract',
  prepareStep: 'Prepare',
  restartStep: 'Restart',
  waitingForRestart: 'Waiting for ChatCMD to restart…',
  updaterReady: 'Ready',
  updaterUnavailable: 'No suitable package',
  checksumVerified: 'Checksum verified',
};

export type UpdateCopy = typeof en;

export function updateCopy(): UpdateCopy {
  return en;
}
